name: Deployment to kopasite.net

on:
  push:
    branches:
      - master

jobs:
  build:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    name: ssh into server and pull from repo
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.SSH_PATH }}
          git pull
